export const LOAD_BAND_INFO_STARTED = 'LOAD_BAND_INFO_STARTED';
export const LOAD_BAND_INFO_COMPLETED = 'LOAD_BAND_INFO_COMPLETED';
export const LOAD_BAND_INFO_FAILED = 'LOAD_BAND_INFO_FAILED';

export const SET_ACTIVE_TRACK = 'SET_ACTIVE_TRACK';
export const SET_ACTIVE_WIKI_TRACK = 'SET_ACTIVE_WIKI_TRACK';
export const SET_COLLAPSED_SONG_GROUP = 'SET_COLLAPSED_SONG_GROUP';

export const SET_IS_PLAYING = 'SET_IS_PLAYING';
export const SET_MASTER_MODE = 'SET_MASTER_MODE';
export const SET_REPEAT_MODE = 'SET_REPEAT_MODE';
export const SET_RANDOM_MODE = 'SET_RANDOM_MODE';
export const SET_CURRENT_PLAY_TIME = 'SET_CURRENT_PLAY_TIME';
